swagger: '2.0'
info:
  title: Sport classifier
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json

paths:
  /predictions:
    post:
      operationId: app.post_predictions
      summary: Predicts sports categories of the most populair sports in the world
      parameters:
        - name: query
          in: body
          schema:
            type: array
            items:
              $ref: '#/definitions/Query'
      responses:
        200:
          description: Returns predicted categories
          schema:
            type: array
            items:
              $ref: '#/definitions/Prediction'
      security:
        - basic: []
securityDefinitions:
  basic:
    type: basic
    x-basicInfoFunc: app.basic_auth

definitions:
  Prediction:
    type: object
    required:
      - category
      - text
    properties:
      category:
        type: string
        description: Predicted category of the sport
        example: "http://examepl.com/sport/jpb"
        readOnly: true
      text:
        type: string
        description: query text
        example: "http://exmaple.com/sport.jpg"
        readOnly: true
  Query:
    type: object
    required:
      - text
    properties:
      text:
        type: string
        description: url to predict
